### ISSUE TITLE
Snooze - Mute issues

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#21]
Gents - I really don't know who to assign this to - but this is becoming a big issue, mainly because no one seems to "get it" and also because no one seems to be testing this with any real understanding.

@kevinlee85 @dakshatechnologies 

All I want you to do is spend 10 minutes testing this so you can understand how flawed and confusing the current implementation is.   
(also you will notice the constant crashing!)

1.Nearby Friends
-------------------
In the simulation, you will see a list of 3 nearby friends.  No icons next to them.  Good.

There should be a <MUTE><SNOOZE>button at the bottom.  This implies that pressing one or the other will affect all the users in the list.

tap <SNOOZE>

Now it says <SNOOZE> [OFF]
(very confusing!!) - did I snooze them or not!!!
(no icons appear next to the users in the list ... so I guess they are not snoozed)

SO .. I tap [OFF]   (very counterintuitive)
I choose 5 mins
now, all snooze icons show.   
but on the screen says
<MUTE><UNSNOOZE>[5 mins]
very confusing.

PS - even though I pressed SNOOZE for 5 mins (and the icons are showing) - Cyrano STILL Announces the friends nearby !!

----
So - snooze-icons are showing  (and I did press snooze) ... 
but when I go view the screen for an individual friend
it says "Mute Status Off"

---- 

conclusion ... 
this is a mess.

And it concerns more that the internal logic is not working, and also that the UI issues are not more obvious to the developers testing.

**Comment by kevinlee85** [comment]
Hi cj:
Did the individual snooze button works as expected?

**Comment by kevinlee85** [comment]
HI CJ:
As i said, i add flags to differ the snooze all and snooze individual process, so i think my commit should not mess other parts.
I recalled you asked me to add snooze all as what the individual snooze did.
And i added as it.
Could you help clarify the correct manipulation of snooze all and un snooze all?
Then I changed the logitech parts as your expected correct manipulations.

List that:
If you press snooze all, then what the app should do?
If you select 15 minus, then what the app should do?

Thank you.

**Comment by kevinlee85** [comment]
Fixed by "Cyrano_05_21_2015_01.apk"

**Comment by cjcornell** [comment]
Not fixed.

When I Mute all  ... or Snooze all - 

when i go to the detail screen for any user  (right after mute-all or snooze-all)  the status in the detail screen does not reflect what just happened.  

After a Mute-All, every individual user should show a Mute status.
After a Snooze-All, every individual user should show Snooze Status with the # minutes remaining.

Honestly - it appears as if you are just changing some icons on the Nearby Friends list, and not setting Mute/Snooze internally.

@kevinlee85 
@dakshatechnologies

**Comment by kevinlee85** [comment]
Hi CJ:
I just reproduce what you said. But i didn't see the problem. After i select mute all, then select one of friend in the friend list, the friend's state show as MUTE.
Snooze also did the same thing.

**Comment by kevinlee85** [comment]
Let i said. Please wait 2 or 3 seconds during your first enter friend list screen because a lot of backend threads is setting the friends' status.

**Comment by kevinlee85** [comment]
Then all the four buttons should works as you expected.

**Comment by cjcornell** [comment]
It looks like there was a change to the REST code (or polling code).   
Because when I tested this morning, all the buttons work.
Thank you.
This issue is closed.  I will close it on Elance too ... and assign another.
Glad this is finally done.
This is one reason why I have the first milestone the way it is.  The others should be more straight forward now, and easier going ...
