### ISSUE TITLE
Snooze-All  / Mute all Buttons 

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#4]
Snooze-All button (on top of the list of nearby friends) needs to work just like the Snooze Button on the individual "friend" screen ... with the option for the ## mins to snooze.  (as per the spec)

**Comment by kevinlee85** [comment]
Fixed.

**Comment by cjcornell** [comment]
Not Fixed.

Bug/Issue Report
Based on Build Tested:
Cyrano_05_13_2015_01.apk
(latest build available, at the time of testing)

Snooze Button, when tapped -
as per pec:
 "just like the Snooze Button on the individual "friend" screen "

*with the option for the ## mins to snooze. (as per the spec)

**Comment by kevinlee85** [comment]
Hi CJ:
It should show "## mins to snooze" which i tested before, let me try it one more time.

**Comment by kevinlee85** [comment]
Hi CJ:
I installed Cyrano_05_13_2015_01.apk again.
When you pressed Snooze All, a drop down opinion will show up, it show 6 opinions for you.
OFF, 5min, 10min, 15min, 30min, 60min for you to choose.
You didn't see those opinions on your side?

**Comment by cjcornell** [comment]
I see it now.  (if the UI is not obvious - you should send me a note)
But there are still issues ... maybe 
When I press "Snooze" - even though "OFF" appears the icons for snooze appear  (they should not appear until I actually choose a snooze time.

However there is a problem - and I dont think it is a UI issue ....
when I visit the indiviudual page for any nearby user ... it doies not give any indication that the user has been snoozed.

so far this is the only problem.

Minor - could you move the this UI to the bottom of the screen?  (without affecting the list display if it needs to scroll

sorry i did not see the rest of the features earlier

**Comment by kevinlee85** [comment]
HI CJ:
Ok, i am continue investigating about your mentioned issue.
I have question, what you means move the ui to bottom of the screen?
Make it looks like display the "Mute All" & "Snooze All" be pinned at the bottom of the Friend list page?

**Comment by cjcornell** [comment]
Yes,  Pinned to the bottom,

**Comment by kevinlee85** [comment]
Hi CJ:
Try it with the last version.

**Comment by cjcornell** [comment]
@dakshatechnologies   and @kevinlee85 
The latest version has an issue with "Snooze"  and I am not sure who is most responsible for fixing it.

@kevinlee85  added a "Snooze all" button  at the bottom of the Nearby Friends list.   And using this button allows is to apply "snooze" nn-minutes to all the users in that list.  The icon next to each friend reflect the new snooze status, as does the message below reflect the number of minutes remaining.

But when I go to the screen for any individual friend.  This screen is not showing that they are "snoozed"  (nor shows minutes remaining or gives me an option for un-snoozing this one single user).    I think that this is definitely not a UI problem but more of a problem with internally tracking the snooze status.

Oh @kevinlee85 - the red message at the bottom of the list (snoozed 15 mins, for instance) - should only be a temporary confirmation. after setting up snooze all.   There is no need to have this message persist, because having it persist will inevitably be inaccurate  (if I UNsnooze just one of the Friends etc... then that status message is inaccurate).

**Comment by kevinlee85** [comment]
Hi CJ:
Okay, i will remove the "red message" when you select any individual friend, and make the snooze button be checked which give you a chance to uncheck the snooze button.

**Comment by kevinlee85** [comment]
Hi CJ:
Okay, i will remove the "red message" when you select any individual friend, and make the snooze button be checked which give you a chance to uncheck the snooze button.

**Comment by cjcornell** [comment]
I think the red message is OK as a confirmation right after they press snooze-all.  Just not something that should persist.

**Comment by cjcornell** [comment]
The UNSnooze option does not quite work as expected - and does not work when we go from Snooze-All ... Unsnooze, and Later back to Snooze-All

**Comment by kevinlee85** [comment]
Ok, i am going to check out why it not works as expected.

**Comment by kevinlee85** [comment]
Already fixed by the last release version.
